module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#e8fff0',
        'surface-dim': '#b8e4cc',
        'surface-bright': '#e8fff0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#d1fee5',
        'surface-container': '#ccf8df',
        'surface-container-high': '#c6f2da',
        'surface-container-highest': '#c1ecd4',
        'on-surface': '#002114',
        'on-surface-variant': '#3f4943',
        'inverse-surface': '#0e3727',
        'inverse-on-surface': '#cffbe2',
        outline: '#6f7a72',
        'outline-variant': '#bec9c0',
        'surface-tint': '#116c4a',
        primary: '#0b6947',
        'on-primary': '#ffffff',
        'primary-container': '#30835f',
        'on-primary-container': '#f5fff6',
        'inverse-primary': '#86d7ad',
        secondary: '#605f50',
        'on-secondary': '#ffffff',
        'secondary-container': '#e6e3d0',
        'on-secondary-container': '#666556',
        tertiary: '#7d532d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#986b42',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdcc1',
        'tertiary-fixed-dim': '#f3bb8d',
        'on-tertiary-fixed': '#2e1500',
        'on-tertiary-fixed-variant': '#643e1a',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#e8fff0',
        'on-background': '#002114',
      },
      fontFamily: {
        lexend: ['Lexend', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em' }],
        'headline-sm': ['20px', { lineHeight: '28px' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'label-lg': ['14px', { lineHeight: '16px', letterSpacing: '0.02em' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.04em' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        margin: '1.25rem',
        gutter: '1rem',
      },
    },
  },
  plugins: [],
}
